<a href="https://colab.research.google.com/github/Kamali1265/ML-Ops-Tasks/blob/main/DAY-4/save_and_load_model_using_pickle_and_joblib_traffic_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h2 style="color:green" align="center">Machine Learning With Python: Save And Load Trained Model</h2>

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression

df = pd.read_csv("traffic.csv")

model = LinearRegression()

model.fit(df[['vehicle_count']], df['duration'])

LinearRegression()

In [ ]:
print(model.coef_)
print(model.intercept_)

[0.2]
-7.105427357601002e-15


In [ ]:
model.predict([[300]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([60.])

In [ ]:
import pickle

with open('traffic_model_pickle', 'wb') as file:
    pickle.dump(model, file)

<h3 style='color:purple'>Save Model To a File Using Python Pickle</h3>

In [ ]:
import pickle

In [ ]:
with open('traffic_model_pickle', 'wb') as file:
    pickle.dump(model, file)

<h4 style='color:purple'>Load Saved Model</h4>

In [ ]:
with open('traffic_model_pickle', 'rb') as file:
    tm = pickle.load(file)

In [ ]:
tm.coef_

array([0.2])

In [ ]:
tm.intercept_

np.float64(-7.105427357601002e-15)

In [ ]:
tm.predict([[400]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([80.])

# Save Trained Model Using joblib

In [ ]:
import joblib

In [ ]:
joblib.dump(model, 'traffic_model_joblib')

['traffic_model_joblib']

<h4 style='color:purple'>Load Saved Model</h4>

In [ ]:
tm = joblib.load('traffic_model_joblib')

In [ ]:
tm.coef_

array([0.2])

In [ ]:
tm.intercept_

np.float64(-7.105427357601002e-15)

In [ ]:
tm.predict([[500]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([100.])